### ISSUE TITLE
Which alignment method and advice on correct settings for your BIDS files in physio toolbox

### ISSUE THREAD

**Issue by InekePillet** [lukassnoek/scanphyslog2bids#2]
Hi

First of all thank you for writing this code! 

I have physiology log files from a 7T Philips MRI (with a 3DEPI sequence for functional scans). 
Within these files, there is ppu and respiratory data. In addition, in the mark column, there are the following markers present 1x ‘0010’, 1x ‘0020’ and many times ‘0002’. 
No other info is present in the log files. As far as I understand, this means there is no gradient log present. 
If it matters, the TR is 1.37 and the number of dynamics is 333 and there were 5 dummy scans at the start. 

I struggle with two issues.

1.
Since my dataset is BIDS compliant, I also want my log files to be made into BIDS compliant files. Thus, I would like to use your code. However, I’m unsure which method to use given the log files I have? Interpolate or vol_markers?

2.
I have used the physio toolbox on Philips log files by following the settings used in the 7T PPU example from this toolbox. The only thing I had to do differently was change the scan/physlog time synchronization from gradient-log to nominal. 
I have also now looked at the 3T example the physio toolbox gives for when you have a BIDS file. The settings here look different from those in the 7T PPU example for Philips log files.
I’m unsure what settings I need to use with the BIDS files that I receive by using your code. 

I have tried the settings from the BIDS example and then ran the physio toolbox on the BIDS file that I got from your code (using the interpolate method). However, the output figures look somewhat different to the figures that I got from running the physio toolbox on the Philips log-file. 
Using the BIDS file, the physio toolbox seemed to use physiology data that is a couple of msecs earlier than when using the Philips log file. The physiological regressors matrix also looks a little different.

Thus, I would like to get your advice on how to us the physio toolbox correctly with the BIDS files your code yields, if that is alright.   
a.	More specifically, is it ok to leave log-scan-timing and sampling-interval empty? 
b.	In addition, relative-start-acquisition, should this be 0 or empty? This was a setting that did not matter when I used the physio toolbox on Philips log files. 
c.	The align-scan parameter, I normally just set this to ‘last’ when using the Philips log file; but in the BIDS example from the physio toolbox, this is ‘first’. I’m unsure what your code does to the log file and thus also unsure if it is wiser to use ‘first’ or ‘last’? 
d.	Ndummies, I should still set this parameter to 5, right, no matter if it’s a BIDS or log file?
e.	The Scan/physlog time synchronization: normally I had to set this to nominal when I used the log file, but now this parameter is just set to ‘scan-timing-log’; is that OK? 

Thank you in advance for your time and also again, for you code!

Kind regards,
Ineke

**Comment by lukassnoek** [comment]
Hi Ineke,

Happy to help. To answer your questions:

1. Because there's no gradient present (and no volume markers, which is an experimental feature from the neuroimaging centre I scanned at), you should use the _interpolate_ option.
2. Hmm, I didn't use the trigger/volume onset estimation method from the PhysIO toolbox because, for my data, it didn't handle the dummy scans properly. As such, the RETROICOR/HRV/RVT output from PhysIO may differ when the triggers were estimated using the PhysIO toolbox itself and the `scanphyslog2bids` package. A couple of msec, however, won't matter given the sluggishness of the HRF. So I won't worry about that

2a. Yes
2b. Not sure. The PhysIO default should be fine
2c. My code interpolates relative to the _last_ trigger. This is because, in my experience, the first trigger (and detecting dummy scans) is quite unreliable and varies across scanners. So I recommend using "last".
2d. When using `scanphyslog2bids`, Ndummies should be set to 0.
2e. Doesn't matter. When `physio.log_files.vendor = 'BIDS'`, this is ignored.

Good luck!

**Comment by InekePillet** [comment]
Great, thank you!

**Comment by InekePillet** [comment]
Great, thank you so much!
